In [1]:
import tensorflow as tf
from numpy.random import RandomState

#### 1. 定义神经网络的相关参数和变量。

In [2]:
batch_size = 8
x = tf.placeholder(tf.float32, shape=(None, 2), name="x-input")
y_ = tf.placeholder(tf.float32, shape=(None, 1), name='y-input')
w1= tf.Variable(tf.random_normal([2, 1], stddev=1, seed=1))
y = tf.matmul(x, w1)

#### 2. 设置自定义的损失函数。

In [3]:
# 定义损失函数使得预测少了的损失大，于是模型应该偏向多的方向预测。
loss_less = 10
loss_more = 1
loss = tf.reduce_sum(tf.select(tf.greater(y, y_), (y - y_) * loss_more, (y_ - y) * loss_less))
train_step = tf.train.AdamOptimizer(0.001).minimize(loss)

#### 3. 生成模拟数据集。

In [4]:
rdm = RandomState(1)
X = rdm.rand(128,2)
Y = [[x1+x2+rdm.rand()] for (x1, x2) in X]

#### 4. 训练模型。

In [5]:
with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    STEPS = 5000
    for i in range(STEPS):
        start = (i*batch_size) % 128
        end = (i*batch_size) % 128 + batch_size
        sess.run(train_step, feed_dict={x: X[start:end], y_: Y[start:end]})
        if i % 1000 == 0:
            print("After %d training step(s), w1 is: " % (i))
            print sess.run(w1), "\n"
    print "Final w1 is: \n", sess.run(w1)

After 0 training step(s), w1 is: 
[[-0.81031823]
 [ 1.4855988 ]] 

After 1000 training step(s), w1 is: 
[[ 0.10801763]
 [ 2.33051562]] 

After 2000 training step(s), w1 is: 
[[ 0.69744456]
 [ 2.66114545]] 

After 3000 training step(s), w1 is: 
[[ 1.01532638]
 [ 2.6881988 ]] 

After 4000 training step(s), w1 is: 
[[ 1.29930842]
 [ 2.56087017]] 

Final w1 is: 
[[ 1.50898325]
 [ 2.31391478]]


#### 5. 重新定义损失函数，使得预测多了的损失大，于是模型应该偏向少的方向预测。

In [6]:
loss_less = 1
loss_more = 10
loss = tf.reduce_sum(tf.select(tf.greater(y, y_), (y - y_) * loss_more, (y_ - y) * loss_less))
train_step = tf.train.AdamOptimizer(0.001).minimize(loss)

with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    STEPS = 5000
    for i in range(STEPS):
        start = (i*batch_size) % 128
        end = (i*batch_size) % 128 + batch_size
        sess.run(train_step, feed_dict={x: X[start:end], y_: Y[start:end]})
        if i % 1000 == 0:
            print("After %d training step(s), w1 is: " % (i))
            print sess.run(w1), "\n"
    print "Final w1 is: \n", sess.run(w1)

After 0 training step(s), w1 is: 
[[-0.81031823]
 [ 1.4855988 ]] 

After 1000 training step(s), w1 is: 
[[ 0.06754676]
 [ 1.68602526]] 

After 2000 training step(s), w1 is: 
[[ 0.62151301]
 [ 1.49415982]] 

After 3000 training step(s), w1 is: 
[[ 0.85797542]
 [ 1.32460475]] 

After 4000 training step(s), w1 is: 
[[ 1.01017809]
 [ 1.2008121 ]] 

Final w1 is: 
[[ 1.08652937]
 [ 1.13757098]]
